language: node_js
node_js:
  - 'node'
cache:
  directories:
    - ~/.npm
stages:
  - test
  - release
jobs:
  include:
    - stage: test
      node_js: lts/*
      script:
        - npm test
        - npm run docs
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: out
        on:
          branch: master
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
        on:
          branch: master
notifications:
  email: false
